---
- name: Main server
  hosts: all_nodes
  become: true

  tasks:
    - name: update cache
      apt:
        update_cache: yes
    - name: install needed packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - gnupg
          - git
        state: present
    - name: make dir for keyrings
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: download gpg key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: "0644"

    - name: add official repo
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_facts['distribution_release'] }} stable"
        state: present
        filename: docker

    - name: install docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present
        update_cache: yes

    - name: enable docker in systemd
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: add user to the docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

- name: Config main server
  become: true
  hosts: main_server
  vars:
    k3s_args: "--disable servicelb --disable traefik"
  tasks:
    - name: Installation required dependencies
      apt:
        name:
          - cgroup-tools
        state: present
        update_cache: yes
    - name: Install k3s
      shell: |
        curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="{{ k3s_args }}" sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Wait for K3s node to become Ready
      shell: k3s kubectl get nodes | grep -q "Ready"
      register: k3s_ready
      until: k3s_ready.rc == 0
      retries: 10
      delay: 5

    - name: Configure kubectl permissions for ubuntu user
      file:
        path: /home/ubuntu/.kube
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: "0755"

    - name: Copy K3s kubeconfig to ubuntu user directory
      copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        owner: ubuntu
        group: ubuntu
        mode: "0600"

    - name: Adjust kubeconfig to use localhost
      replace:
        path: /home/ubuntu/.kube/config
        regexp: "127.0.0.1"
        replace: "localhost"
#----------------------------------------------------------
- name: Config worker servers
  become: true
  hosts: worker_nodes
  tasks:
    - name: Copy compose.yml
      copy:
        src: ../compose_files/worker_nodes/
        dest: /srv/www/
        mode: "0644"
        owner: ubuntu
        group: ubuntu
