[main_server]
main_node ansible_host=misek.duckdns.org ansible_user=ubuntu

[worker_nodes]
worker_node_1 ansible_host=misek2.duckdns.org ansible_user=ubuntu
#worker_node_2 ansible_host=misek3.duckdns.org ansible_user=ubuntu

[all_nodes:children]
main_server
worker_nodes